version: '3.8'

services:
 
 backend:
  image: backend-backend
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  depends_on:
   - db

 db:
  image: mysql:8.0
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '3906:3306'
  expose:
   - '3906'
  volumes:
   - my-db:/var/lib/mysql
volumes:
  my-db: