services:

 frontend:
  container_name: frontend
  image: janus-frontend
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "443:443"
   - "81:80"
  volumes:
   - ./frontend/certs:/https
   - ./data/images:/app/public/images
  environment:
   - HTTPS=${HTTPS}
   - SSL_CRT_FILE=${SSL_CRT_FILE}
   - SSL_KEY_FILE=${SSL_KEY_FILE}

 backend:
  container_name: backend
  image: janus-backend
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "82:9000"
  volumes:
   - ./backend/certs:/https
   - ./data/images:/app/data/images
   - ./data/files:/app/data/files
   - ./data/trees:/app/data/trees
  user: root
  depends_on:
   - db
  environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ALLOWED_CORS_ORIGINS=${ALLOWED_CORS_ORIGINS}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - JWT__SecretKey_Web=${JWT__SecretKey_Web}
      - JWT__SecretKey_CLI=${JWT__SecretKey_CLI}
      - BlacklistCleanup=${BlacklistCleanup}
      - FILE_STORAGE_PATH=/app/data/files
      - TREE_STORAGE_PATH=/app/data/trees
  networks:
      - intranet


 db:
  container_name: db
  image: mysql:8.0
  restart: always
  environment:
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
   - '83:3306'
  expose:
   - '3906'
  volumes:
   - ./data/db:/var/lib/mysql
  networks:
      - intranet

volumes:
  janus-db:
  profile-pictures:
  
networks:
  intranet:
   driver: bridge