version: '3.8'

services:

 frontend:
  container_name: frontend
  image: janus-frontend
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "443:443"
   - "81:80"
  volumes:
   - ./frontend/certs:/https
   - ./data/images:/app/public/images
  environment:
   - HTTPS=true
   - SSL_CRT_FILE=https/frontend-certificate.crt
   - SSL_KEY_FILE=https/frontend-private-nopass.key

 backend:
  container_name: backend
  image: janus-backend
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "82:9000"
  volumes:
   - ./backend/certs:/https
   - ./data/images:/app/data/images
   - ./data/files:/app/data/files
   - ./data/trees:/app/data/trees
  user: root
  depends_on:
   - db
  environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=db;User=user;Password=password;
      - ALLOWED_CORS_ORIGINS=http://localhost:81
      - ASPNETCORE_URLS=https://+:9000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/backend-certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=sZF8H6h+08iW3ZJ4n/9w4nv+tH2kPanzVFSjc5yK6J0=
      - JWT__Issuer=yourIssuer
      - JWT__Audience=yourAudience
      - JWT__SecretKey_Web=MySecureKeyWithAtLeastThirtyTwoCharacters
      - JWT__SecretKey_CLI=MySecureKeyWithAtLeastThirtyTwoCharacters
      - BlacklistCleanup=30
      - FILE_STORAGE_PATH=/app/data/files
      - TREE_STORAGE_PATH=/app/data/trees
  networks:
      - intranet


 db:
  container_name: db
  image: mysql:8.0
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '83:3306'
  expose:
   - '3906'
  volumes:
   - ./data/db:/var/lib/mysql
  networks:
      - intranet

volumes:
  janus-db:
  profile-pictures:
  
networks:
  intranet:
   driver: bridge