version: '3.8'
services:
 db:
  image: mysql:8.0
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '3906:3306'
  expose:
   - '3906'
  volumes:
   - my-db:/var/lib/mysql
volumes:
  my-db: